#!/bin/bash

# Exit if any pre-commit scripts fail
set -e

# Execute each pre-commit file in order
for f in .git/hooks/pre-commit.d/*.sh; do
    echo "Running $f"
    if [ -x $f ] && [ -f $f ]; then
        $f
    fi
done
