#!/bin/bash

set -e
#python3 $HOME/.git-templates/tools/multihooks.py
#for f in $(find -L ./pre-commit.d/ -maxdepth 1 -type f); do
for f in $(find -L .git/hooks/pre-commit.d/ -maxdepth 1 -type f); do
    $f
done
